In [ ]:
Encoding Categorical Variables in Python

Encoding categorical variables is a crucial step in preparing data for machine learning models, as most algorithms require numerical input. Categorical data can be classified into nominal (no inherent order, e.g., colors) and ordinal (ordered, e.g., education levels). Below are common encoding techniques and their use cases:

Label Encoding

Label Encoding assigns a unique integer to each category. It is suitable for ordinal data where the order of categories is meaningful.

from sklearn.preprocessing import LabelEncoder

data = ['red', 'blue', 'green', 'blue', 'red']
label_encoder = LabelEncoder()
encoded_data = label_encoder.fit_transform(data)
print(encoded_data)
Copy
Output:

[2 0 1 0 2]
Copy
One-Hot Encoding

One-Hot Encoding converts categories into binary vectors, making it ideal for nominal data without any inherent order.

from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(['red', 'blue', 'green', 'blue', 'red']).reshape(-1, 1)
onehot_encoder = OneHotEncoder(sparse=False)
encoded_data = onehot_encoder.fit_transform(data)
print(encoded_data)
Copy
Output:

[[0. 1. 0.]
[1. 0. 0.]
[0. 0. 1.]
[1. 0. 0.]
[0. 1. 0.]]
Copy
Ordinal Encoding

Ordinal Encoding is similar to Label Encoding but explicitly preserves the order of categories, making it suitable for ordinal data.

from sklearn.preprocessing import OrdinalEncoder

data = np.array(['low', 'medium', 'high', 'medium', 'low']).reshape(-1, 1)
ordinal_encoder = OrdinalEncoder(categories=[['low', 'medium', 'high']])
encoded_data = ordinal_encoder.fit_transform(data)
print(encoded_data)
Copy
Output:

[[0.]
[1.]
[2.]
[1.]
[0.]]
Copy
Binary Encoding

Binary Encoding combines Label Encoding and binary representation, reducing dimensionality for high-cardinality features.

from category_encoders import BinaryEncoder
import pandas as pd

data = pd.DataFrame({'City': ['Delhi', 'Mumbai', 'Hyderabad', 'Chennai', 'Bangalore']})
binary_encoder = BinaryEncoder(cols=['City'])
encoded_data = binary_encoder.fit_transform(data)
print(encoded_data)
Copy
Frequency Encoding

Frequency Encoding replaces each category with its frequency in the dataset, useful for high-cardinality features.

data = pd.DataFrame({'category': ['A', 'B', 'A', 'C', 'B', 'A']})
frequency = data['category'].value_counts(normalize=True)
data['encoded'] = data['category'].map(frequency)
print(data)
Copy
Output:

category encoded
0 A 0.500000
1 B 0.333333
2 A 0.500000
3 C 0.166667
4 B 0.333333
5 A 0.500000
Copy
Choosing the Right Encoding Method

Use One-Hot Encoding or Frequency Encoding for nominal data.

Use Label Encoding or Ordinal Encoding for ordinal data.

For high-cardinality features, consider Binary Encoding or Target Encoding.

Important Considerations

Dimensionality: One-Hot Encoding can lead to high dimensionality for features with many categories.

Overfitting: Target Encoding may cause overfitting, especially with small datasets.

Model Compatibility: Tree-based models often handle categorical data directly, while linear models may require careful encoding to avoid multicollinearity.

By selecting the appropriate encoding technique based on the nature of your data and the machine learning model, you can ensure better performance and meaningful insights.