In [2]:
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
# array[start:end:step]
print(array[0])
print(array[-4])

[1 2 3 4]
[1 2 3 4]


In [4]:
print(array[0:3])
# start index will not be included only row 0,1,2 will be printed not row 3

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(array[0:4:1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
print(array[0:4:2])
print('             ')
print(array[::-1])

[[ 1  2  3  4]
 [ 9 10 11 12]]
             
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [14]:
print(array[0,0])
#  this prints first row first col element
#  if u want thethe elements in first col in ever row
print(array[:,0])
print('     ')
print(array[:,-1])

1
[ 1  5  9 13]
     
[ 4  8 12 16]


In [15]:
print(array[: , 0:3])
#  this means the row is from beigning but the col is from 0 to 3 that means col0,1,2

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [16]:
print(array[: , ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
