In [4]:
# Scalar arethematic
import numpy as np
arr=np.array([1,2,3])
print(arr+1)
print(arr*2)
print(arr/3)
print(arr **2)

[2 3 4]
[2 4 6]
[0.33333333 0.66666667 1.        ]
[1 4 9]


In [8]:
# Vectorized math functions

print(np.sqrt(arr))
a=np.array([1.29,3.22])
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))
print(np.pi)

[1.         1.41421356 1.73205081]
[1. 3.]
[1. 3.]
[2. 4.]
3.141592653589793


In [9]:
radii=np.array([1,2,3])
print(np.pi* radii **2)
# pi r square area of circle

[ 3.14159265 12.56637061 28.27433388]


In [13]:
#element wise arthematic
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [16]:
# comparison operators
scorces=np.array([91,55,100,73,82,64])
print(scorces==100)
print(scorces>=60)
# very intresting
scorces[scorces<60]=0
print(scorces)

[False False  True False False False]
[ True False  True  True  True  True]
[ 91   0 100  73  82  64]
