In [5]:
import numpy as np
# Brodcasting allows Numpy to perform operations on arrays with different shapes by virtually expanding dimensions 
# so they match the longer arryas shape
# to broadcast the conditions should be like below
# the dimensions have the same size ex:(2,4) and (2,4)
# or
# one of the dimensions has size 1 ex:(1,4) and (4,1)
# with shapes like (2,4) and (4,1) cannot be broadcasted


arr1=np.array([[1,2,3,4]])# 1 row with 4 col
arr2=np.array([[1],[2],[3],[4]])# 4 rows with 1 col
print(arr1.shape)
print(arr2.shape)

(1, 4)
(4, 1)


In [6]:
print(arr1*arr2)


[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
