In [5]:
import numpy as np
# Filtering = Refers to the process of selecting elements from an array that match a given condition

ages=np.array([[21,17,19,20,16,30,18,65],
               [39,22,15,99,18,19,20,21]])

teenagers=ages[ages<18]
adults=ages[(ages>=18)&(ages<65)]# the 2d shape is lost
even=ages[ages%2==0]
odds=ages[ages%2==1]
print(teenagers)
print(adults)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]


In [7]:
adults=np.where(ages>=18,ages,0)
# this willretain the original shape of the array where  the unsatisfied condition elements will be replaced with 0
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
