In [2]:
# reshape()
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
a=np.reshape(arr,(3,2))
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
print(b) # Output: [1 2 3 4]

[1 2 3 4]


In [7]:
# flatten()
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = a.flatten(order='C')
print(b) # Output: [1 2 3 4]

[1 2 3 4]


In [8]:
# transpose()
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = a.transpose()
print(b) # Output: [1 2 3 4]

[[1 3]
 [2 4]]


In [12]:
# cocatenate()
import numpy as np
a = np.array([[1, 2], [3, 4]])
b=np.array([[5,6]])
a=np.concatenate((a,b),axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
# split()
import numpy as np
a = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])
b=np.array_split(a,3)
print(b)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [16]:
a=np.array([1,2,3,4,5])
mean=np.mean(a)
std=np.std(a)
print(mean)
print(std)
# mean()
# median()
# std()
# min()
# max()
# sum()

3.0
1.4142135623730951


In [24]:
r=np.random.rand()
# rando
ra=np.random.randint(1,7)
print(r)
print(ra)

[[[0.42279707]
  [0.52835807]
  [0.70618738]
  [0.23014185]
  [0.19747059]
  [0.59141243]
  [0.01380653]]]
2
